export const districtConfig = {
  name: '中心商业区',
  buildings: [
    {
      id: 'b001',
      name: '万达商业广场',
      type: 'commercial',
      position: [0, 0],
      size: [12, 10],
      floors: 12,
      info: {
        area: 52000,
        occupancy: 0.92,
        mainBusiness: '综合购物、餐饮、娱乐',
        dailyFlow: 45000,
        avgRent: 28,
        developer: '万达集团',
        openYear: 2018,
      }
    },
    {
      id: 'b002',
      name: '金融中心大厦',
      type: 'office',
      position: [14, -8],
      size: [10, 10],
      floors: 25,
      info: {
        area: 78000,
        occupancy: 0.88,
        mainBusiness: '银行、证券、保险',
        dailyFlow: 12000,
        avgRent: 45,
        developer: '中信集团',
        openYear: 2020,
      }
    },
    {
      id: 'b003',
      name: '星光天地购物中心',
      type: 'retail',
      position: [-12, 8],
      size: [10, 8],
      floors: 6,
      info: {
        area: 35000,
        occupancy: 0.95,
        mainBusiness: '品牌零售、精品百货',
        dailyFlow: 32000,
        avgRent: 35,
        developer: '星光集团',
        openYear: 2016,
      }
    },
    {
      id: 'b004',
      name: '创智科技园',
      type: 'office',
      position: [10, 14],
      size: [8, 8],
      floors: 18,
      info: {
        area: 42000,
        occupancy: 0.82,
        mainBusiness: '科技企业孵化、研发中心',
        dailyFlow: 8000,
        avgRent: 38,
        developer: '科创集团',
        openYear: 2021,
      }
    },
    {
      id: 'b005',
      name: '翡翠花园住宅区',
      type: 'residential',
      position: [-12, -10],
      size: [10, 8],
      floors: 8,
      info: {
        area: 65000,
        occupancy: 0.96,
        mainBusiness: '高端住宅、配套商业',
        dailyFlow: 15000,
        avgRent: 22,
        developer: '万科集团',
        openYear: 2019,
      }
    },
    {
      id: 'b006',
      name: '国际商务中心',
      type: 'commercial',
      position: [2, -16],
      size: [10, 8],
      floors: 20,
      info: {
        area: 58000,
        occupancy: 0.90,
        mainBusiness: '国际商务办公、会议中心',
        dailyFlow: 10000,
        avgRent: 52,
        developer: '华润集团',
        openYear: 2022,
      }
    },
    {
      id: 'b007',
      name: '美食商业街',
      type: 'retail',
      position: [4, 12],
      size: [12, 4],
      floors: 3,
      info: {
        area: 18000,
        occupancy: 0.98,
        mainBusiness: '特色餐饮、小吃街',
        dailyFlow: 28000,
        avgRent: 30,
        developer: '美食城集团',
        openYear: 2017,
      }
    },
    {
      id: 'b008',
      name: '湖畔酒店公寓',
      type: 'residential',
      position: [-14, 16],
      size: [8, 6],
      floors: 15,
      info: {
        area: 22000,
        occupancy: 0.85,
        mainBusiness: '高端酒店式公寓',
        dailyFlow: 3000,
        avgRent: 65,
        developer: '洲际集团',
        openYear: 2020,
      }
    },
  ],

  roads: [
    {
      id: 'r001',
      name: '外环路',
      path: [[55, 0], [39, 39], [0, 55], [-39, 39], [-55, 0], [-39, -39], [0, -55], [39, -39]],
      width: 8,
      type: 'main',
      closed: true,
    },
    {
      id: 'r002',
      name: '内环路',
      path: [[32, 0], [23, 23], [0, 32], [-23, 23], [-32, 0], [-23, -23], [0, -32], [23, -23]],
      width: 6,
      type: 'main',
      closed: true,
    },
    {
      id: 'r003',
      name: '北连接路',
      path: [[0, 32], [0, 55]],
      width: 5,
      type: 'secondary',
    },
    {
      id: 'r004',
      name: '东连接路',
      path: [[32, 0], [55, 0]],
      width: 5,
      type: 'secondary',
    },
    {
      id: 'r005',
      name: '南连接路',
      path: [[0, -32], [0, -55]],
      width: 5,
      type: 'secondary',
    },
    {
      id: 'r006',
      name: '西连接路',
      path: [[-32, 0], [-55, 0]],
      width: 5,
      type: 'secondary',
    },
    {
      id: 'r007',
      name: '东北连接路',
      path: [[23, 23], [39, 39]],
      width: 4,
      type: 'secondary',
    },
    {
      id: 'r008',
      name: '西北连接路',
      path: [[-23, 23], [-39, 39]],
      width: 4,
      type: 'secondary',
    },
    {
      id: 'r009',
      name: '东南连接路',
      path: [[23, -23], [39, -39]],
      width: 4,
      type: 'secondary',
    },
    {
      id: 'r010',
      name: '西南连接路',
      path: [[-23, -23], [-39, -39]],
      width: 4,
      type: 'secondary',
    },
  ],

  greenery: [
    { id: 'g001', category: 'park', position: [-38, 30], size: [12, 10] },
    { id: 'g002', category: 'park', position: [38, -30], size: [10, 10] },
    { id: 'g003', category: 'lawn', center: [20, 38], radius: 5 },
    { id: 'g004', category: 'lawn', center: [-20, -38], radius: 5 },
    { id: 'g005', category: 'lawn', center: [38, 20], radius: 4 },
    { id: 'g006', category: 'lawn', center: [-38, -20], radius: 4 },
    { id: 'g007', category: 'tree', position: [-8, -4], scale: 1.2, type: 'deciduous' },
    { id: 'g008', category: 'tree', position: [6, -3], scale: 0.9, type: 'coniferous' },
    { id: 'g009', category: 'tree', position: [-4, 4], scale: 1.0, type: 'deciduous' },
    { id: 'g010', category: 'tree', position: [8, 6], scale: 1.1, type: 'deciduous' },
    { id: 'g011', category: 'tree', position: [-6, 12], scale: 0.8, type: 'coniferous' },
    { id: 'g012', category: 'tree', position: [16, -16], scale: 1.0, type: 'deciduous' },
    { id: 'g013', category: 'tree', position: [-16, 16], scale: 0.9, type: 'coniferous' },
    { id: 'g014', category: 'tree', position: [25, 25], scale: 1.3, type: 'deciduous' },
    { id: 'g015', category: 'tree', position: [-25, -25], scale: 1.1, type: 'deciduous' },
    { id: 'g016', category: 'tree', position: [25, -25], scale: 1.0, type: 'deciduous' },
    { id: 'g017', category: 'tree', position: [-25, 25], scale: 0.9, type: 'coniferous' },
    { id: 'g018', category: 'lawn', center: [0, 25], radius: 3 },
    { id: 'g019', category: 'lawn', center: [0, -25], radius: 3 },
  ],
}

export const annotationData = [
  {
    id: 'ann001',
    targetId: 'b001',
    position: { x: 0, y: 36, z: 0 },
    title: '万达商业广场',
    content: '区域核心商业综合体，日均客流4.5万人次',
    color: 0xff6644,
  },
  {
    id: 'ann002',
    targetId: 'b002',
    position: { x: 14, y: 75, z: -8 },
    title: '金融中心大厦',
    content: '甲级写字楼，入驻率88%，平均租金45元/㎡/天',
    color: 0x4488ff,
  },
  {
    id: 'ann003',
    targetId: 'b003',
    position: { x: -12, y: 18, z: 8 },
    title: '星光天地购物中心',
    content: '精品零售为主，入驻率95%，日均客流3.2万人次',
    color: 0xffaa22,
  },
  {
    id: 'ann004',
    targetId: 'b007',
    position: { x: 4, y: 9, z: 12 },
    title: '美食商业街',
    content: '特色餐饮聚集地，入驻率98%，日均客流2.8万人次',
    color: 0xff4488,
  },
]

export const scenePresets = {
  overview: {
    name: '总览视角',
    position: [80, 60, 80],
    target: [0, 0, 0],
  },
  commercial: {
    name: '商业中心',
    position: [10, 25, 25],
    target: [0, 10, 0],
  },
  office: {
    name: '办公区域',
    position: [45, 30, -10],
    target: [25, 30, 0],
  },
  residential: {
    name: '住宅区域',
    position: [-55, 20, -15],
    target: [-35, 10, -15],
  },
  dining: {
    name: '美食街区',
    position: [20, 15, 40],
    target: [10, 5, 25],
  },
}
